name:                mapalgebra
version:             1.0.0
synopsis:            Map Algebra types and common operations.
description:         Map Algebra types and common operations.
homepage:            https://github.com/fosskers/mapalgebra
license:             BSD3
author:              Colin Woodbury
maintainer:          colin@fosskers.ca
copyright:           2018 Colin Woodbury
category:            Geography

extra-source-files:
  - README.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns
  # These introduce around a 2x speedup.
  # - -fno-liberate-case
  # - -funfolding-use-threshold1000
  # - -funfolding-keeness-factor1000
  # - -fllvm

dependencies:
  - base >= 4.7 && < 4.12
  - bytestring
  - containers
  - data-default
  - deepseq
  - JuicyPixels >= 3.2 && < 3.3
  - massiv >= 0.1 && < 0.2
  - vector >= 0.11 && < 0.13

library:
  source-dirs:       lib

tests:
  mapalgebra-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - mapalgebra
      - tasty >= 0.11 && < 2.0
      - tasty-hunit >= 0.9 && < 0.11
      - tasty-quickcheck >= 0.8 && < 0.10

benchmarks:
  mapalgebra-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -O2
      - -with-rtsopts=-N
    dependencies:
      - criterion >= 1.1 && < 1.3
      - mapalgebra
